remote_theme: WildCodeSchool/workshops-jekyll-theme

# disable the jekyll-titles-from-headings plugin, 
# so first h1 will not be used as prior title of you page
titles_from_headings:
  enabled: false

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default" # possible values: default or tic-tac

style: dev # possible values: dev, data, ciber, design or wild.
title: 'Les requêtes AJAX dans un projet PHP'
description: 'Requêter le serveur, traiter la demande et modifier le DOM '
# type: ''
main_image: 'bank-phrom-Tzm3Oyu_6sk-unsplash.jpg' # http or relative path to image
show_clone: true
show_toc: true
lang: en